/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { PostedContextWithGenerationId } from "./PostedContextWithGenerationId";
import { PostedContextWithUtterances } from "./PostedContextWithUtterances";

export const Context: core.serialization.Schema<serializers.tts.Context.Raw, Hume.tts.Context> =
    core.serialization.undiscriminatedUnion([PostedContextWithGenerationId, PostedContextWithUtterances]);

export declare namespace Context {
    type Raw = PostedContextWithGenerationId.Raw | PostedContextWithUtterances.Raw;
}
