/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const MillisecondInterval: core.serialization.ObjectSchema<
    serializers.tts.MillisecondInterval.Raw,
    Hume.tts.MillisecondInterval
> = core.serialization.object({
    begin: core.serialization.number(),
    end: core.serialization.number(),
});

export declare namespace MillisecondInterval {
    export interface Raw {
        begin: number;
        end: number;
    }
}
