/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { VoiceProvider } from "./VoiceProvider.js";

export const PostedUtteranceVoiceWithId: core.serialization.ObjectSchema<
    serializers.tts.PostedUtteranceVoiceWithId.Raw,
    Hume.tts.PostedUtteranceVoiceWithId
> = core.serialization.object({
    id: core.serialization.string(),
    provider: VoiceProvider.optional(),
});

export declare namespace PostedUtteranceVoiceWithId {
    export interface Raw {
        id: string;
        provider?: VoiceProvider.Raw | null;
    }
}
