/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { VoiceProvider } from "./VoiceProvider";

export const ReturnVoice: core.serialization.ObjectSchema<serializers.tts.ReturnVoice.Raw, Hume.tts.ReturnVoice> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        provider: VoiceProvider.optional(),
    });

export declare namespace ReturnVoice {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        provider?: VoiceProvider.Raw | null;
    }
}
