/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { TimestampMessage } from "./TimestampMessage";
import { SnippetAudioChunk } from "./SnippetAudioChunk";

export const TtsOutput: core.serialization.Schema<serializers.tts.TtsOutput.Raw, Hume.tts.TtsOutput> =
    core.serialization.undiscriminatedUnion([TimestampMessage, SnippetAudioChunk]);

export declare namespace TtsOutput {
    export type Raw = TimestampMessage.Raw | SnippetAudioChunk.Raw;
}
