// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const PostedUserDefinedToolVersion: core.serialization.Schema<
    serializers.empathicVoice.PostedUserDefinedToolVersion.Raw,
    Hume.empathicVoice.PostedUserDefinedToolVersion
> = core.serialization.object({
    description: core.serialization.string().optional(),
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    parameters: core.serialization.string(),
    versionDescription: core.serialization.property("version_description", core.serialization.string().optional()),
});

export declare namespace PostedUserDefinedToolVersion {
    export interface Raw {
        description?: string | null;
        fallback_content?: string | null;
        parameters: string;
        version_description?: string | null;
    }
}
