// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "get_current_temperature"
 *     }
 */
export interface PostedUserDefinedToolName {
    /**
     * Name of the built-in tool to use. Hume supports the following built-in tools:
     *
     * - **web_search:** enables EVI to search the web for up-to-date information when applicable.
     * - **hang_up:** closes the WebSocket connection when appropriate (e.g., after detecting a farewell in the conversation).
     *
     * For more information, see our guide on [using built-in tools](/docs/speech-to-speech-evi/features/tool-use#using-built-in-tools).
     */
    name: string;
}
