/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CustomModelId } from "./CustomModelId";
import { CustomModelVersionId } from "./CustomModelVersionId";
export declare const CustomModel: core.serialization.Schema<
    serializers.expressionMeasurement.batch.CustomModel.Raw,
    Hume.expressionMeasurement.batch.CustomModel
>;
export declare namespace CustomModel {
    type Raw = CustomModelId.Raw | CustomModelVersionId.Raw;
}
