/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../core";
import { CustomModelId } from "./CustomModelId";
import { CustomModelVersionId } from "./CustomModelVersionId";
export const CustomModel = core.serialization.undiscriminatedUnion([CustomModelId, CustomModelVersionId]);
