/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../core";
import { RegistryFileDetail } from "./RegistryFileDetail";
export const EmbeddingGenerationBaseRequest = core.serialization.object({
    registryFileDetails: core.serialization.property(
        "registry_file_details",
        core.serialization.list(RegistryFileDetail).optional(),
    ),
});
