/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../core";
import { TranscriptionMetadata } from "./TranscriptionMetadata";
import { GroupedPredictionsNerPrediction } from "./GroupedPredictionsNerPrediction";
export const PredictionsOptionalTranscriptionMetadataNerPrediction = core.serialization.object({
    metadata: TranscriptionMetadata.optional(),
    groupedPredictions: core.serialization.property(
        "grouped_predictions",
        core.serialization.list(GroupedPredictionsNerPrediction),
    ),
});
