/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../core";
export const SortBy = core.serialization.enum_(["created", "started", "ended"]);
