/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Url } from "./Url";
export declare const SourceUrl: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.SourceUrl.Raw,
    Hume.expressionMeasurement.batch.SourceUrl
>;
export declare namespace SourceUrl {
    interface Raw extends Url.Raw {}
}
