/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Queued } from "./Queued";
export declare const StateEmbeddingGenerationQueued: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.StateEmbeddingGenerationQueued.Raw,
    Hume.expressionMeasurement.batch.StateEmbeddingGenerationQueued
>;
export declare namespace StateEmbeddingGenerationQueued {
    interface Raw extends Queued.Raw {}
}
