/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../core";
import { StateTlInferenceQueued } from "./StateTlInferenceQueued";
import { StateTlInferenceInProgress } from "./StateTlInferenceInProgress";
import { StateTlInferenceCompletedTlInference } from "./StateTlInferenceCompletedTlInference";
import { StateTlInferenceFailed } from "./StateTlInferenceFailed";
export const StateTlInference = core.serialization
    .union("status", {
        QUEUED: StateTlInferenceQueued,
        IN_PROGRESS: StateTlInferenceInProgress,
        COMPLETED: StateTlInferenceCompletedTlInference,
        FAILED: StateTlInferenceFailed,
    })
    .transform({
        transform: (value) => value,
        untransform: (value) => value,
    });
