/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
export declare const TimeInterval: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.TimeInterval.Raw,
    Hume.expressionMeasurement.batch.TimeInterval
>;
export declare namespace TimeInterval {
    interface Raw {
        begin: number;
        end: number;
    }
}
