// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { PostedConfigEventMessagesOnInactivityTimeout } from "./PostedConfigEventMessagesOnInactivityTimeout.js";
import { PostedConfigEventMessagesOnMaxDurationTimeout } from "./PostedConfigEventMessagesOnMaxDurationTimeout.js";
import { PostedConfigEventMessagesOnNewChat } from "./PostedConfigEventMessagesOnNewChat.js";

export const PostedConfigEventMessages: core.serialization.ObjectSchema<
    serializers.empathicVoice.PostedConfigEventMessages.Raw,
    Hume.empathicVoice.PostedConfigEventMessages
> = core.serialization.object({
    onInactivityTimeout: core.serialization.property(
        "on_inactivity_timeout",
        PostedConfigEventMessagesOnInactivityTimeout.optional(),
    ),
    onMaxDurationTimeout: core.serialization.property(
        "on_max_duration_timeout",
        PostedConfigEventMessagesOnMaxDurationTimeout.optional(),
    ),
    onNewChat: core.serialization.property("on_new_chat", PostedConfigEventMessagesOnNewChat.optional()),
});

export declare namespace PostedConfigEventMessages {
    export interface Raw {
        on_inactivity_timeout?: PostedConfigEventMessagesOnInactivityTimeout.Raw | null;
        on_max_duration_timeout?: PostedConfigEventMessagesOnMaxDurationTimeout.Raw | null;
        on_new_chat?: PostedConfigEventMessagesOnNewChat.Raw | null;
    }
}
