/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../../../../../index";
/**
 * Response for the speech prosody emotion model.
 */
export interface StreamModelPredictionsProsody {
    predictions?: Hume.expressionMeasurement.stream.StreamModelPredictionsProsodyPredictionsItem[];
}
