/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../../../../../index";
/**
 * Response for the vocal burst emotion model.
 */
export interface StreamModelPredictionsBurst {
    predictions?: Hume.expressionMeasurement.stream.StreamModelPredictionsBurstPredictionsItem[];
}
