/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../index";
import * as Hume from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
export declare const PostedConfigName: core.serialization.Schema<
    serializers.empathicVoice.PostedConfigName.Raw,
    Hume.empathicVoice.PostedConfigName
>;
export declare namespace PostedConfigName {
    interface Raw {
        name: string;
    }
}
