/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
export const PostedEventMessageSpec = core.serialization.object({
    enabled: core.serialization.boolean(),
    text: core.serialization.string().optional(),
});
