/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
export declare const ReturnUserDefinedToolVersionType: core.serialization.Schema<
    serializers.empathicVoice.ReturnUserDefinedToolVersionType.Raw,
    Hume.empathicVoice.ReturnUserDefinedToolVersionType
>;
export declare namespace ReturnUserDefinedToolVersionType {
    type Raw = "FIXED" | "LATEST";
}
