/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ReturnPrompt } from "./ReturnPrompt";
export const ReturnPagedPrompts = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
    promptsPage: core.serialization.property("prompts_page", core.serialization.list(ReturnPrompt.optional())),
});
