/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
export declare const ReturnNudgeSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnNudgeSpec.Raw,
    Hume.empathicVoice.ReturnNudgeSpec
>;
export declare namespace ReturnNudgeSpec {
    interface Raw {
        enabled: boolean;
        interval_secs?: number | null;
    }
}
