/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ReturnPromptVersionType } from "./ReturnPromptVersionType";
export const ReturnPrompt = core.serialization.object({
    name: core.serialization.string(),
    id: core.serialization.string(),
    text: core.serialization.string(),
    version: core.serialization.number(),
    versionDescription: core.serialization.property("version_description", core.serialization.string().optional()),
    versionType: core.serialization.property("version_type", ReturnPromptVersionType),
    createdOn: core.serialization.property("created_on", core.serialization.number()),
    modifiedOn: core.serialization.property("modified_on", core.serialization.number()),
});
