/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { Context } from "./Context";
import { AudioConfiguration } from "./AudioConfiguration";
import { Tool } from "./Tool";
import { BuiltinToolConfig } from "./BuiltinToolConfig";
import { SessionSettingsVariablesValue } from "./SessionSettingsVariablesValue";
export const SessionSettings = core.serialization.object({
    type: core.serialization.stringLiteral("session_settings"),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    systemPrompt: core.serialization.property("system_prompt", core.serialization.string().optional()),
    context: Context.optional(),
    audio: AudioConfiguration.optional(),
    languageModelApiKey: core.serialization.property("language_model_api_key", core.serialization.string().optional()),
    tools: core.serialization.list(Tool).optional(),
    builtinTools: core.serialization.property("builtin_tools", core.serialization.list(BuiltinToolConfig).optional()),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    variables: core.serialization.record(core.serialization.string(), SessionSettingsVariablesValue).optional(),
});
