/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ToolType } from "./ToolType";
export const ToolCallMessage = core.serialization.object({
    name: core.serialization.string(),
    parameters: core.serialization.string(),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    type: core.serialization.stringLiteral("tool_call"),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    toolType: core.serialization.property("tool_type", ToolType.optional()),
    responseRequired: core.serialization.property("response_required", core.serialization.boolean()),
});
