/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ToolType } from "./ToolType";
import { ErrorLevel } from "./ErrorLevel";
export const ToolErrorMessage = core.serialization.object({
    type: core.serialization.stringLiteral("tool_error"),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    toolType: core.serialization.property("tool_type", ToolType.optional()),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    content: core.serialization.string().optional(),
    error: core.serialization.string(),
    code: core.serialization.string().optional(),
    level: ErrorLevel.optional(),
});
