/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
export declare const WebSocketError: core.serialization.ObjectSchema<
    serializers.empathicVoice.WebSocketError.Raw,
    Hume.empathicVoice.WebSocketError
>;
export declare namespace WebSocketError {
    interface Raw {
        type: "error";
        custom_session_id?: string | null;
        code: string;
        slug: string;
        message: string;
        request_id?: string | null;
    }
}
