// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const PostedConfigName: core.serialization.Schema<
    serializers.empathicVoice.PostedConfigName.Raw,
    Omit<Hume.empathicVoice.PostedConfigName, "id">
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace PostedConfigName {
    export interface Raw {
        name: string;
    }
}
