/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../index";
export interface Inference {
    /**
     * Prosody model inference results.
     *
     * EVI uses the prosody model to measure 48 emotions related to speech and vocal characteristics within a given expression.
     */
    prosody?: Hume.empathicVoice.ProsodyInference;
}
