/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Versioning method for a Prompt. Either `FIXED` for using a fixed version number or `LATEST` for auto-updating to the latest version.
 */
export type ReturnPromptVersionType = "FIXED" | "LATEST";
export declare const ReturnPromptVersionType: {
    readonly Fixed: "FIXED";
    readonly Latest: "LATEST";
};
