/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../index";
/**
 * A paginated list of prompt versions returned from the server
 */
export interface ReturnPagedPrompts {
    /**
     * The page number of the returned list.
     *
     * This value corresponds to the `page_number` parameter specified in the request. Pagination uses zero-based indexing.
     */
    pageNumber: number;
    /**
     * The maximum number of items returned per page.
     *
     * This value corresponds to the `page_size` parameter specified in the request.
     */
    pageSize: number;
    /** The total number of pages in the collection. */
    totalPages: number;
    /** List of prompts returned for the specified `page_number` and `page_size`. */
    promptsPage: (Hume.empathicVoice.ReturnPrompt | undefined)[];
}
