/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../index";
export interface Tool {
    /** Type of tool. Set to `function` for user-defined tools. */
    type: Hume.empathicVoice.ToolType;
    /** Name of the user-defined tool to be enabled. */
    name: string;
    /**
     * Parameters of the tool. Is a stringified JSON schema.
     *
     * These parameters define the inputs needed for the tool's execution, including the expected data type and description for each input field. Structured as a JSON schema, this format ensures the tool receives data in the expected format.
     */
    parameters: string;
    /** An optional description of what the tool does, used by the supplemental LLM to choose when and how to call the function. */
    description?: string;
    /** Optional text passed to the supplemental LLM if the tool call fails. The LLM then uses this text to generate a response back to the user, ensuring continuity in the conversation. */
    fallbackContent?: string;
}
