/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../index";
export type WebhookEvent = Hume.empathicVoice.WebhookEventChatStarted | Hume.empathicVoice.WebhookEventChatEnded;
