// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { ChatClient } from "../resources/chat/client/Client.js";
import { ChatGroupsClient } from "../resources/chatGroups/client/Client.js";
import { ChatsClient } from "../resources/chats/client/Client.js";
import { ConfigsClient } from "../resources/configs/client/Client.js";
import { ControlPlaneClient } from "../resources/controlPlane/client/Client.js";
import { PromptsClient } from "../resources/prompts/client/Client.js";
import { ToolsClient } from "../resources/tools/client/Client.js";

export declare namespace EmpathicVoiceClient {
    export interface Options extends BaseClientOptions {}
}

export class EmpathicVoiceClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EmpathicVoiceClient.Options>;
    protected _controlPlane: ControlPlaneClient | undefined;
    protected _chatGroups: ChatGroupsClient | undefined;
    protected _chats: ChatsClient | undefined;
    protected _configs: ConfigsClient | undefined;
    protected _prompts: PromptsClient | undefined;
    protected _tools: ToolsClient | undefined;
    protected _chat: ChatClient | undefined;

    constructor(options: EmpathicVoiceClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get controlPlane(): ControlPlaneClient {
        return (this._controlPlane ??= new ControlPlaneClient(this._options));
    }

    public get chatGroups(): ChatGroupsClient {
        return (this._chatGroups ??= new ChatGroupsClient(this._options));
    }

    public get chats(): ChatsClient {
        return (this._chats ??= new ChatsClient(this._options));
    }

    public get configs(): ConfigsClient {
        return (this._configs ??= new ConfigsClient(this._options));
    }

    public get prompts(): PromptsClient {
        return (this._prompts ??= new PromptsClient(this._options));
    }

    public get tools(): ToolsClient {
        return (this._tools ??= new ToolsClient(this._options));
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }
}
