// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "<role>You are an updated version of an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
 *         versionDescription: "This is an updated version of the Weather Assistant Prompt."
 *     }
 */
export interface PostedPromptVersion {
    /** Text used for this version of the Prompt. */
    text: string;
    /** Description that is appended to a specific version of a Prompt. */
    versionDescription?: string;
}
