/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         text: "text"
 *     }
 */
export interface PostedPromptVersion {
  /** Description that is appended to a specific version of a Prompt. */
  versionDescription?: string;
  /** Text used for this version of the Prompt. */
  text: string;
}
