/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../../../index";
export interface EmbeddingGenerationJob extends Hume.expressionMeasurement.batch.JobEmbeddingGeneration {
    type: string;
}
