/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Error_ {
    /** An error message. */
    message: string;
    /** A file path relative to the top level source URL or file. */
    file: string;
}
