/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Hume from "../../../../../index";
export interface PredictionsOptionalTranscriptionMetadataNerPrediction {
    metadata?: Hume.expressionMeasurement.batch.TranscriptionMetadata;
    groupedPredictions: Hume.expressionMeasurement.batch.GroupedPredictionsNerPrediction[];
}
