/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export type TtsOutput = Hume.tts.TtsOutput.Timestamp | Hume.tts.TtsOutput.Audio;

export namespace TtsOutput {
    export interface Timestamp extends Hume.tts.TimestampMessage {
        type: "timestamp";
    }

    export interface Audio extends Hume.tts.SnippetAudioChunk {
        type: "audio";
    }
}
