/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";

export const Ner: core.serialization.ObjectSchema<serializers.customModels.Ner.Raw, Hume.customModels.Ner> =
    core.serialization.object({
        identifySpeakers: core.serialization.property("identify_speakers", core.serialization.boolean().optional()),
    });

export declare namespace Ner {
    interface Raw {
        identify_speakers?: boolean | null;
    }
}
