/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";
import { InProgress } from "./InProgress";

export const StateEmbeddingGenerationInProgress: core.serialization.ObjectSchema<
    serializers.customModels.StateEmbeddingGenerationInProgress.Raw,
    Hume.customModels.StateEmbeddingGenerationInProgress
> = core.serialization.object({}).extend(InProgress);

export declare namespace StateEmbeddingGenerationInProgress {
    interface Raw extends InProgress.Raw {}
}
