/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VoicesListRequestProvider = "HUME_AI" | "CUSTOM_VOICE";

export const VoicesListRequestProvider = {
    HumeAi: "HUME_AI",
    CustomVoice: "CUSTOM_VOICE",
} as const;
