/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Completed {
    /** When this job was created (Unix timestamp in milliseconds). */
    created_timestamp_ms: number;
    /** When this job started (Unix timestamp in milliseconds). */
    started_timestamp_ms: number;
    /** When this job ended (Unix timestamp in milliseconds). */
    ended_timestamp_ms: number;
    /** The number of predictions that were generated by this job. */
    num_predictions: number;
    /** The number of errors that occurred while running this job. */
    num_errors: number;
}
