/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "..";

export interface FacePrediction {
    /** Frame number */
    frame: number;
    /** Time in seconds when face detection occurred. */
    time: number;
    /** The predicted probability that a detected face was actually a face. */
    prob: number;
    box: Hume.BoundingBox;
    /** A high-dimensional embedding in emotion space. */
    emotions: Hume.EmotionScore[];
    /** FACS 2.0 features and their scores. */
    facs?: Hume.FacsScore[];
    /** Modality-specific descriptive features and their scores. */
    descriptions?: Hume.DescriptionsScore[];
}
