/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ModelsWarning {
    /** Warning message text. */
    warning?: string;
    /** Unique identifier for the error. */
    code?: string;
}
