/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Queued {
    /** When this job was created (Unix timestamp in milliseconds). */
    created_timestamp_ms: number;
}
