/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";
import { InferencePrediction } from "./InferencePrediction";
import { Error_ } from "./Error_";

export const InferenceResults: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.InferenceResults.Raw,
    Hume.expressionMeasurement.InferenceResults
> = core.serialization.object({
    predictions: core.serialization.list(InferencePrediction),
    errors: core.serialization.list(Error_),
});

export declare namespace InferenceResults {
    interface Raw {
        predictions: InferencePrediction.Raw[];
        errors: Error_.Raw[];
    }
}
