/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../index';
import * as Hume from '../../../../api/index';
import * as core from '../../../../core';
import { ToxicityItem } from './ToxicityItem';

export const Toxicity: core.serialization.Schema<
  serializers.expressionMeasurement.Toxicity.Raw,
  Hume.expressionMeasurement.Toxicity
> = core.serialization.list(ToxicityItem);

export declare namespace Toxicity {
  type Raw = ToxicityItem.Raw[];
}
