/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";
import { Bcp47Tag } from "./Bcp47Tag";

export const TranscriptionMetadata: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.TranscriptionMetadata.Raw,
    Hume.expressionMeasurement.TranscriptionMetadata
> = core.serialization.object({
    confidence: core.serialization.number(),
    detectedLanguage: core.serialization.property("detected_language", Bcp47Tag.optional()),
});

export declare namespace TranscriptionMetadata {
    interface Raw {
        confidence: number;
        detected_language?: Bcp47Tag.Raw | null;
    }
}
