/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * File details
 */
export interface AuthorizedFile {
    /** Hume-generated File ID */
    id: string;
    /** File name */
    name?: string;
    /** File URI */
    uri?: string;
    /** File upload URI */
    uploadUri?: string;
    /** File thumbnail URI */
    thumbnailUri?: string;
    /** Hume-generated User ID */
    userId: string;
    /** File type: video, audio, video_no_audio, image, text, or mediapipe_facemesh */
    dataType: string;
    /** Created date and time */
    createdOn?: number;
    /** Updated date and time */
    modifiedOn?: number;
    /** Additional details as key, value pairs */
    metadata?: Record<string, Record<string, unknown>>;
    /** Flag which denotes whether the file is stored with Hume */
    humeStorage?: boolean;
    /** Timestamp denoting when the file was uploaded to Hume */
    humeStorageUploadTimestamp?: number;
    /** Indicates whether this file has been sanitized for sharing */
    isSanitized: boolean;
    /** Indicates whether this file is owned by the current file reader */
    isOwnedByReader: boolean;
    /** Indicates whether this file is linked to a model that is publicly shared */
    isLinkedToPubliclyShared?: boolean;
    /** Indicates whether this file is linked to a Hume-owned model that is publicly shared */
    isLinkedToHumeModel?: boolean;
}
