/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Feature types as key, value pairs
 */
export type DatasetLabelsFileUriInputFeatureTypesValue = "CATEGORICAL" | "NUMERIC" | "TEXT" | "DATETIME" | "UNDEFINED";

export const DatasetLabelsFileUriInputFeatureTypesValue = {
    Categorical: "CATEGORICAL",
    Numeric: "NUMERIC",
    Text: "TEXT",
    Datetime: "DATETIME",
    Undefined: "UNDEFINED",
} as const;
