/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * List of Tags associated with the Model version
 */
export interface ExternalModelVersionTag {
    /** Tag name (key) */
    key: string;
    /** Tag description (value) */
    value: string;
}
