/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export interface PredictionsOptionalNullFacePrediction {
    metadata?: Hume.customModels.Null;
    groupedPredictions: Hume.customModels.GroupedPredictionsFacePrediction[];
}
