/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export interface PredictionsOptionalTranscriptionMetadataNerPrediction {
    metadata?: Hume.customModels.TranscriptionMetadata;
    groupedPredictions: Hume.customModels.GroupedPredictionsNerPrediction[];
}
