/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../..";

export type StateTraining =
    | Hume.customModels.StateTraining.Queued
    | Hume.customModels.StateTraining.InProgress
    | Hume.customModels.StateTraining.Completed
    | Hume.customModels.StateTraining.Failed;

export declare namespace StateTraining {
    interface Queued extends Hume.customModels.StateTrainingQueued {
        status: "QUEUED";
    }

    interface InProgress extends Hume.customModels.StateTrainingInProgress {
        status: "IN_PROGRESS";
    }

    interface Completed extends Hume.customModels.StateTrainingCompletedTraining {
        status: "COMPLETED";
    }

    interface Failed extends Hume.customModels.StateTrainingFailed {
        status: "FAILED";
    }
}
