/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export interface TlInferenceResults {
    predictions: Hume.customModels.TlInferencePrediction[];
    errors: Hume.customModels.Error_[];
}
