/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../..";

export interface TrainingBaseRequest {
    customModel: Hume.customModels.CustomModelRequest;
    dataset: Hume.customModels.Dataset;
    targetFeature?: string;
    task?: Hume.customModels.Task;
    evaluation?: Hume.customModels.EvaluationArgs;
    alternatives?: Hume.customModels.Alternative[];
    callbackUrl?: string;
    notify?: boolean;
}
