/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

/**
 * When provided, the output is an assistant message.
 */
export interface AssistantMessage {
    customSessionId?: string;
    /** Indicates if this message was constructed from a text input message. */
    fromText: boolean;
    /** ID of the assistant message. */
    id?: string;
    /** Transcript of the message. */
    message: Hume.empathicVoice.ChatMessage;
    /** Inference model results. */
    models: Hume.empathicVoice.Inference;
    type: "assistant_message";
}
