/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * When provided, the output is an assistant end message.
 */
export interface AssistantEnd {
    customSessionId?: string;
    type: "assistant_end";
}
