/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * When provided, the output is audio.
 */
export interface AudioOutput {
    /** The type of message sent through the socket; for an Audio Output message, this must be `audio_output`. */
    type: "audio_output";
    /** Used to manage conversational state, correlate frontend and backend data, and persist conversations across EVI sessions. */
    customSessionId?: string;
    /** ID of the audio output. */
    id: string;
    /** Base64 encoded audio output. */
    data: string;
}
