// This file was auto-generated by Fern from our API Definition.

/**
 * **Base64 encoded audio output.** This encoded audio is transmitted to the client, where it can be decoded and played back as part of the user interaction. The returned audio format is WAV and the sample rate is 48kHz.
 *
 * Contains the audio data, an ID to track and reference the audio output, and an index indicating the chunk position relative to the whole audio segment. See our [Audio Guide](/docs/speech-to-speech-evi/guides/audio) for more details on preparing and processing audio.
 */
export interface AudioOutput {
    /** Used to manage conversational state, correlate frontend and backend data, and persist conversations across EVI sessions. */
    customSessionId?: string;
    /** Base64 encoded audio output. This encoded audio is transmitted to the client, where it can be decoded and played back as part of the user interaction. */
    data: string;
    /** ID of the audio output. Allows the Audio Output message to be tracked and referenced. */
    id: string;
    /** Index of the chunk of audio relative to the whole audio segment. */
    index: number;
    type: "audio_output";
}
