/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export interface AudioConfiguration {
    /** Audio encoding. */
    encoding: Hume.empathicVoice.Encoding;
    /** Number of channels. */
    channels: number;
    /** Audio sample rate. */
    sampleRate: number;
}
