/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BodyCustomLanguageModelSupportsToolUseV0EviCustomLanguageModelSupportsToolUsePost {
    modelResource: string;
}
