// This file was auto-generated by Fern from our API Definition.

/**
 * The type of message sent through the socket; for a Chat Metadata message, this must be `chat_metadata`.
 *
 * The Chat Metadata message is the first message you receive after establishing a connection with EVI and contains important identifiers for the current Chat session.
 */
export const ChatMetadataType = {
    ChatMetadata: "chat_metadata",
} as const;
export type ChatMetadataType = (typeof ChatMetadataType)[keyof typeof ChatMetadataType];
