/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ContextType = "persistent" | "temporary";
export const ContextType = {
    Persistent: "persistent",
    Temporary: "temporary",
} as const;
