// This file was auto-generated by Fern from our API Definition.

export const ContextType = {
    Persistent: "persistent",
    Temporary: "temporary",
} as const;
export type ContextType = (typeof ContextType)[keyof typeof ContextType];
