/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ModelProviderEnum =
    | "GROQ"
    | "OPEN_AI"
    | "FIREWORKS"
    | "ANTHROPIC"
    | "CUSTOM_LANGUAGE_MODEL"
    | "GOOGLE"
    | "HUME_AI"
    | "AMAZON_BEDROCK";
export const ModelProviderEnum = {
    Groq: "GROQ",
    OpenAi: "OPEN_AI",
    Fireworks: "FIREWORKS",
    Anthropic: "ANTHROPIC",
    CustomLanguageModel: "CUSTOM_LANGUAGE_MODEL",
    Google: "GOOGLE",
    HumeAi: "HUME_AI",
    AmazonBedrock: "AMAZON_BEDROCK",
} as const;
