/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Events this URL is subscribed to
 */
export type PostedWebhookEventType = "chat_started" | "chat_ended";

export const PostedWebhookEventType = {
    ChatStarted: "chat_started",
    ChatEnded: "chat_ended",
} as const;
