/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A nudge specification posted to the server
 */
export interface PostedNudgeSpec {
    /** EVI will nudge user after inactivity */
    enabled?: boolean;
    /** Time interval in seconds after which the nudge will be sent. */
    intervalSecs?: number;
}
