/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A tool name change to be posted to the server
 */
export interface PostedToolName {
    /** Name applied to all versions of a particular Tool. */
    name?: string;
}
