// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

/**
 * Collection of timeout specifications returned by the server.
 *
 * Timeouts are sent by the server when specific time-based events occur during a chat session. These specifications set the inactivity timeout and the maximum duration an EVI WebSocket connection can stay open before it is automatically disconnected.
 */
export interface PostedTimeoutSpecs {
    inactivity?: Hume.empathicVoice.PostedTimeoutSpecsInactivity;
    maxDuration?: Hume.empathicVoice.PostedTimeoutSpecsMaxDuration;
}
