/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

/**
 * A Voice specification posted to the server
 */
export interface PostedVoice {
    /** The provider of the voice to use. */
    provider?: "HUME_AI";
    /** String with the name of the voice to use. */
    name: Hume.empathicVoice.PostedVoiceName;
}
