// This file was auto-generated by Fern from our API Definition.

export const PostedBuiltinToolName = {
    WebSearch: "web_search",
    HangUp: "hang_up",
} as const;
export type PostedBuiltinToolName = (typeof PostedBuiltinToolName)[keyof typeof PostedBuiltinToolName];
