/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A new version of an existing tool to be posted to the server
 */
export interface PostedToolVersion {
    /** Description that is appended to a specific version of a Tool. */
    versionDescription?: string;
    /** Text describing what the tool does. */
    description?: string;
    /** Stringified JSON defining the parameters used by this version of the Tool. */
    parameters: string;
}
