/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A Voice specification posted to the server
 */
export interface PostedVoice {
    /** The provider of the voice to use. Based on the enum VoiceProvider. */
    provider?: string;
    /** String with the name of the voice to use. */
    name: string;
}
