// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

/**
 * Collection of event_message specs to be posted to the server
 */
export interface PostedEventMessageSpecs {
    onInactivityTimeout?: Hume.empathicVoice.PostedEventMessageSpec;
    onMaxDurationTimeout?: Hume.empathicVoice.PostedEventMessageSpec;
    onNewChat?: Hume.empathicVoice.PostedEventMessageSpec;
}
