// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

export interface ProsodyInference {
    /**
     * The confidence scores for 48 emotions within the detected expression of an audio sample.
     *
     * Scores typically range from 0 to 1, with higher values indicating a stronger confidence level in the measured attribute.
     *
     * See our guide on [interpreting expression measures](/docs/speech-to-speech-evi/faq#what-do-evis-expression-labels-and-measures-mean) to learn more.
     */
    scores: Hume.empathicVoice.EmotionScores;
}
