// This file was auto-generated by Fern from our API Definition.

/**
 * Configures nudges, brief audio prompts that can guide conversations when users pause or need encouragement to continue speaking. Nudges help create more natural, flowing interactions by providing gentle conversational cues.
 */
export interface ReturnConfigNudges {
    /** If true, EVI will 'nudge' the user to speak after a determined interval of silence. */
    enabled: boolean;
    /** The interval of inactivity (in seconds) before a nudge is triggered. */
    intervalSecs?: number;
}
