/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A signed URI linking to a file in GCS
 */
export interface ReturnSignedUri {
    filename?: string;
    method?: string;
    signedUri?: string;
    expirationTimestampMillis?: number;
}
