/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A description of current chat chat sessions per tag
 */
export interface ReturnActiveChatCountPerTag {
    /** User tag applied to a chat. */
    tag: string;
    /** The total number of active chats for this user with the specified tag. */
    totalTagActiveChats: number;
}
