// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

/**
 * Map of timeouts associated with this config.
 */
export interface ReturnConfigTimeouts {
    inactivity: Hume.empathicVoice.ReturnTimeoutSpec;
    maxDuration: Hume.empathicVoice.ReturnTimeoutSpec;
}
