// This file was auto-generated by Fern from our API Definition.

export const ReturnUserDefinedToolVersionType = {
    Fixed: "FIXED",
    Latest: "LATEST",
} as const;
export type ReturnUserDefinedToolVersionType =
    (typeof ReturnUserDefinedToolVersionType)[keyof typeof ReturnUserDefinedToolVersionType];
