/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

/**
 * An octave custom voice specification returned from the server
 */
export interface ReturnVoiceOctaveCustom {
    id?: string;
    version?: number;
    name?: string;
    description?: string;
    voiceType?: string;
    createdOn?: number;
    modifiedOn?: number;
    voicePrompt?: string;
    normalizationGainDb?: number;
    speakerEmbedding?: string;
    referenceUri?: string;
    referenceAudioFormat?: string;
    cloneReferenceUri?: string;
    cloneReferenceAudioFormat?: string;
    referenceTokens?: string;
    referenceAtoks?: string;
    referenceDecoderDtoks?: string;
    referenceText?: string;
    signedPreviewReferenceUri?: Hume.empathicVoice.ReturnSignedUri;
    signedCloneReferenceUri?: Hume.empathicVoice.ReturnSignedUri;
    imageUri?: string;
    disabled?: boolean;
}
