// This file was auto-generated by Fern from our API Definition.

export const ReturnPromptVersionType = {
    Fixed: "FIXED",
    Latest: "LATEST",
} as const;
export type ReturnPromptVersionType = (typeof ReturnPromptVersionType)[keyof typeof ReturnPromptVersionType];
