/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the current state of the audio reconstruction job. There are five possible statuses:
 *
 * - `QUEUED`: The reconstruction job is waiting to be processed.
 *
 * - `IN_PROGRESS`: The reconstruction is currently being processed.
 *
 * - `COMPLETE`: The audio reconstruction is finished and ready for download.
 *
 * - `ERROR`: An error occurred during the reconstruction process.
 *
 * - `CANCELED`: The reconstruction job has been canceled.
 */
export type ReturnChatAudioReconstructionStatus = "QUEUED" | "IN_PROGRESS" | "COMPLETE" | "ERROR" | "CANCELLED";
export const ReturnChatAudioReconstructionStatus = {
    Queued: "QUEUED",
    InProgress: "IN_PROGRESS",
    Complete: "COMPLETE",
    Error: "ERROR",
    Cancelled: "CANCELLED",
} as const;
