/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReturnVoiceSpecProvider = "HUME_AI" | "CUSTOM_VOICE";
export const ReturnVoiceSpecProvider = {
    HumeAi: "HUME_AI",
    CustomVoice: "CUSTOM_VOICE",
} as const;
