/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

/**
 * A specific voice specification for use with EVI 1 or 2
 */
export interface ReturnVoiceSpecEvi2 {
    /** The provider of the voice to use. Based on the enum VoiceProvider. */
    provider: string;
    /** String with the name of the voice to use. Maximum length of 75 characters. Will be converted to all-uppercase. */
    name?: string;
    customVoice: Hume.empathicVoice.ReturnVoiceEvi2;
}
