/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A specific nudge configuration returned from the server
 */
export interface ReturnTimeoutSpec {
    /**
     * Boolean indicating if this timeout is enabled.
     *
     * If set to false, EVI will not timeout due to a specified duration being reached. However, the conversation will eventually disconnect after 1,800 seconds (30 minutes), which is the maximum WebSocket duration limit for EVI.
     */
    enabled: boolean;
    /** Time interval in seconds after which the nudge will be sent. */
    intervalSecs?: number;
    durationSecs?: unknown;
}
