// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

/**
 * An Octave voice available for text-to-speech
 */
export interface ReturnVoice {
    id?: string;
    name?: string;
    provider?: Hume.empathicVoice.VoiceProvider;
}
