// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../index.js";

/**
 * A description of chat status with a paginated list of chat events returned from the server
 */
export interface ReturnChatPagedEvents {
    /** Identifier for the Chat Group. Any chat resumed from this Chat will have the same `chat_group_id`. Formatted as a UUID. */
    chatGroupId: string;
    config?: Hume.empathicVoice.ReturnConfigSpec;
    /** Time at which the Chat ended. Measured in seconds since the Unix epoch. */
    endTimestamp?: number;
    /** List of Chat Events for the specified `page_number` and `page_size`. */
    eventsPage: Hume.empathicVoice.ReturnChatEvent[];
    /** Identifier for a Chat. Formatted as a UUID. */
    id: string;
    /** Stringified JSON with additional metadata about the chat. */
    metadata?: string;
    /**
     * The page number of the returned list.
     *
     * This value corresponds to the `page_number` parameter specified in the request. Pagination uses zero-based indexing.
     */
    pageNumber: number;
    /**
     * The maximum number of items returned per page.
     *
     * This value corresponds to the `page_size` parameter specified in the request.
     */
    pageSize: number;
    paginationDirection: Hume.empathicVoice.ReturnChatPagedEventsPaginationDirection;
    /** Time at which the Chat started. Measured in seconds since the Unix epoch. */
    startTimestamp: number;
    status: Hume.empathicVoice.ReturnChatPagedEventsStatus;
    /** The total number of pages in the collection. */
    totalPages: number;
}
