// This file was auto-generated by Fern from our API Definition.

/**
 * A specific event message configuration to be returned from the server
 */
export interface ReturnEventMessageSpec {
    /** Boolean indicating if this event message is enabled. */
    enabled: boolean;
    /** Optional text that will be used as a verbatim event message. If the text is null and the event message is enabled, the system will generate a message based using the language model. */
    text?: string;
}
