/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Role = "assistant" | "system" | "user" | "all" | "tool" | "context";
export const Role = {
    Assistant: "assistant",
    System: "system",
    User: "user",
    All: "all",
    Tool: "tool",
    Context: "context",
} as const;
