/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

/**
 * When provided, the output is a tool call.
 */
export interface ToolCallMessage {
    /** Name of the tool called. */
    name: string;
    /** Parameters of the tool call. Is a stringified JSON schema. */
    parameters: string;
    /** ID of the tool call. */
    toolCallId: string;
    type?: "tool_call";
    customSessionId?: string;
    /** Type of tool called, either 'builtin' or 'function'. */
    toolType: Hume.empathicVoice.ToolType;
    /** Whether a response is required from the developer. */
    responseRequired: boolean;
}
