// This file was auto-generated by Fern from our API Definition.

export interface TurnDetectionSpec {
    endOfTurnSilenceMs?: number;
    prefixPaddingMs?: number;
    speechDetectionThreshold?: number;
}
