/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../index";

export interface VoiceArgs {
    voice?: Hume.empathicVoice.VoiceNameEnum;
    speechRateMultiplier?: number;
    baseline?: boolean;
    reconstruct?: boolean;
    additive?: boolean;
    drift?: boolean;
    model?: Hume.empathicVoice.Model;
}
