// This file was auto-generated by Fern from our API Definition.

/** Always `chat_started`. */
export const WebhookEventChatStartedEventName = {
    ChatStarted: "chat_started",
} as const;
export type WebhookEventChatStartedEventName =
    (typeof WebhookEventChatStartedEventName)[keyof typeof WebhookEventChatStartedEventName];
