// This file was auto-generated by Fern from our API Definition.

/**
 * When provided, the output is an error message.
 */
export interface WebSocketError {
    /** Error code. Identifies the type of error encountered. */
    code: string;
    /** Used to manage conversational state, correlate frontend and backend data, and persist conversations across EVI sessions. */
    customSessionId?: string;
    /** Detailed description of the error. */
    message: string;
    /** ID of the initiating request. */
    requestId?: string;
    /** Short, human-readable identifier and description for the error. See a complete list of error slugs on the [Errors page](/docs/resources/errors). */
    slug: string;
    /**
     * The type of message sent through the socket; for a Web Socket Error message, this must be `error`.
     *
     * This message indicates a disruption in the WebSocket connection, such as an unexpected disconnection, protocol error, or data transmission issue.
     */
    type: "error";
}
