// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const Bcp47Tag: core.serialization.Schema<
    serializers.expressionMeasurement.batch.Bcp47Tag.Raw,
    Hume.expressionMeasurement.batch.Bcp47Tag
> = core.serialization.enum_([
    "zh",
    "da",
    "nl",
    "en",
    "en-AU",
    "en-IN",
    "en-NZ",
    "en-GB",
    "fr",
    "fr-CA",
    "de",
    "hi",
    "hi-Latn",
    "id",
    "it",
    "ja",
    "ko",
    "no",
    "pl",
    "pt",
    "pt-BR",
    "pt-PT",
    "ru",
    "es",
    "es-419",
    "sv",
    "ta",
    "tr",
    "uk",
]);

export declare namespace Bcp47Tag {
    export type Raw =
        | "zh"
        | "da"
        | "nl"
        | "en"
        | "en-AU"
        | "en-IN"
        | "en-NZ"
        | "en-GB"
        | "fr"
        | "fr-CA"
        | "de"
        | "hi"
        | "hi-Latn"
        | "id"
        | "it"
        | "ja"
        | "ko"
        | "no"
        | "pl"
        | "pt"
        | "pt-BR"
        | "pt-PT"
        | "ru"
        | "es"
        | "es-419"
        | "sv"
        | "ta"
        | "tr"
        | "uk";
}
