/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { JobTraining } from "./JobTraining.js";

export const CustomModelsTrainingJob: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.CustomModelsTrainingJob.Raw,
    Hume.expressionMeasurement.batch.CustomModelsTrainingJob
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .extend(JobTraining);

export declare namespace CustomModelsTrainingJob {
    export interface Raw extends JobTraining.Raw {
        type: string;
    }
}
