// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const CustomModelVersionId: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.CustomModelVersionId.Raw,
    Hume.expressionMeasurement.batch.CustomModelVersionId
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace CustomModelVersionId {
    export interface Raw {
        version_id: string;
    }
}
