/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CustomModelVersionId: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.CustomModelVersionId.Raw,
    Hume.expressionMeasurement.CustomModelVersionId
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace CustomModelVersionId {
    interface Raw {
        version_id: string;
    }
}
