/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const EmotionScore: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.EmotionScore.Raw,
    Hume.expressionMeasurement.batch.EmotionScore
> = core.serialization.object({
    name: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace EmotionScore {
    interface Raw {
        name: string;
        score: number;
    }
}
