// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { EmotionScore } from "./EmotionScore.js";

export const FacemeshPrediction: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.FacemeshPrediction.Raw,
    Hume.expressionMeasurement.batch.FacemeshPrediction
> = core.serialization.object({
    emotions: core.serialization.list(EmotionScore),
});

export declare namespace FacemeshPrediction {
    export interface Raw {
        emotions: EmotionScore.Raw[];
    }
}
