/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const Null: core.serialization.Schema<
    serializers.expressionMeasurement.batch.Null.Raw,
    Hume.expressionMeasurement.batch.Null
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace Null {
    export type Raw = Record<string, unknown>;
}
