/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const SourceTextSource: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.SourceTextSource.Raw,
    Hume.expressionMeasurement.SourceTextSource
> = core.serialization.object({});

export declare namespace SourceTextSource {
    interface Raw {}
}
