/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { InProgress } from "./InProgress.js";

export const StateEmbeddingGenerationInProgress: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.StateEmbeddingGenerationInProgress.Raw,
    Hume.expressionMeasurement.batch.StateEmbeddingGenerationInProgress
> = core.serialization.object({}).extend(InProgress);

export declare namespace StateEmbeddingGenerationInProgress {
    export interface Raw extends InProgress.Raw {}
}
