/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { Failed } from "./Failed.js";

export const StateTlInferenceFailed: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.StateTlInferenceFailed.Raw,
    Hume.expressionMeasurement.batch.StateTlInferenceFailed
> = core.serialization.object({}).extend(Failed);

export declare namespace StateTlInferenceFailed {
    export interface Raw extends Failed.Raw {}
}
