// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { Failed } from "./Failed.js";

export const StateEmbeddingGenerationFailed: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.StateEmbeddingGenerationFailed.Raw,
    Hume.expressionMeasurement.batch.StateEmbeddingGenerationFailed
> = core.serialization.object({}).extend(Failed);

export declare namespace StateEmbeddingGenerationFailed {
    export interface Raw extends Failed.Raw {}
}
