// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const TimeInterval: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.TimeInterval.Raw,
    Hume.expressionMeasurement.batch.TimeInterval
> = core.serialization.object({
    begin: core.serialization.number(),
    end: core.serialization.number(),
});

export declare namespace TimeInterval {
    export interface Raw {
        begin: number;
        end: number;
    }
}
