// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { CustomModel } from "./CustomModel.js";

export const TlInferenceBaseRequest: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.TlInferenceBaseRequest.Raw,
    Hume.expressionMeasurement.batch.TlInferenceBaseRequest
> = core.serialization.object({
    customModel: core.serialization.property("custom_model", CustomModel),
    urls: core.serialization.list(core.serialization.string()).optional(),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string().optional()),
    notify: core.serialization.boolean().optional(),
});

export declare namespace TlInferenceBaseRequest {
    export interface Raw {
        custom_model: CustomModel.Raw;
        urls?: string[] | null;
        callback_url?: string | null;
        notify?: boolean | null;
    }
}
