/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const ToxicityScore: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.ToxicityScore.Raw,
    Hume.expressionMeasurement.batch.ToxicityScore
> = core.serialization.object({
    name: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace ToxicityScore {
    export interface Raw {
        name: string;
        score: number;
    }
}
