/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { InferenceSourcePredictResult } from "./InferenceSourcePredictResult.js";

export const UnionPredictResult: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.UnionPredictResult.Raw,
    Hume.expressionMeasurement.batch.UnionPredictResult
> = InferenceSourcePredictResult;

export declare namespace UnionPredictResult {
    export type Raw = InferenceSourcePredictResult.Raw;
}
