/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Target } from "./Target";

export const ValidationArgs: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.batch.ValidationArgs.Raw,
    Hume.expressionMeasurement.batch.ValidationArgs
> = core.serialization.object({
    positiveLabel: core.serialization.property("positive_label", Target.optional()),
});

export declare namespace ValidationArgs {
    interface Raw {
        positive_label?: Target.Raw | null;
    }
}
