/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Hume from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { EmotionEmbeddingItem } from "./EmotionEmbeddingItem.js";

export const EmotionEmbedding: core.serialization.Schema<
    serializers.expressionMeasurement.stream.EmotionEmbedding.Raw,
    Hume.expressionMeasurement.stream.EmotionEmbedding
> = core.serialization.list(EmotionEmbeddingItem);

export declare namespace EmotionEmbedding {
    export type Raw = EmotionEmbeddingItem.Raw[];
}
