/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const EmotionEmbeddingItem: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.stream.EmotionEmbeddingItem.Raw,
    Hume.expressionMeasurement.stream.EmotionEmbeddingItem
> = core.serialization.object({
    name: core.serialization.string().optional(),
    score: core.serialization.number().optional(),
});

export declare namespace EmotionEmbeddingItem {
    export interface Raw {
        name?: string | null;
        score?: number | null;
    }
}
