/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hume from "../../api";
import * as core from "../../core";

export const EmotionEmbedding: core.serialization.Schema<
    serializers.EmotionEmbedding.Raw,
    Hume.EmotionEmbedding
> = core.serialization.list(
    core.serialization.lazyObject(
        async () => (await import("..")).EmotionEmbeddingItem
    )
);

export declare namespace EmotionEmbedding {
    type Raw = serializers.EmotionEmbeddingItem.Raw[];
}
