/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hume from "../../api";
import * as core from "../../core";

export const FacemeshPrediction: core.serialization.ObjectSchema<
    serializers.FacemeshPrediction.Raw,
    Hume.FacemeshPrediction
> = core.serialization.object({
    emotions: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).EmotionScore)),
});

export declare namespace FacemeshPrediction {
    interface Raw {
        emotions: serializers.EmotionScore.Raw[];
    }
}
