/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hume from "../../api";
import * as core from "../../core";

export const ModelsSuccessProsodyPredictionsItem: core.serialization.ObjectSchema<
    serializers.ModelsSuccessProsodyPredictionsItem.Raw,
    Hume.ModelsSuccessProsodyPredictionsItem
> = core.serialization.object({
    time: core.serialization.lazyObject(async () => (await import("..")).TimeRange).optional(),
    emotions: core.serialization.lazy(async () => (await import("..")).EmotionEmbedding).optional(),
});

export declare namespace ModelsSuccessProsodyPredictionsItem {
    interface Raw {
        time?: serializers.TimeRange.Raw | null;
        emotions?: serializers.EmotionEmbedding.Raw | null;
    }
}
