/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hume from "../../api";
import * as core from "../../core";

export const PredictionsOptionalTranscriptionMetadataNerPrediction: core.serialization.ObjectSchema<
    serializers.PredictionsOptionalTranscriptionMetadataNerPrediction.Raw,
    Hume.PredictionsOptionalTranscriptionMetadataNerPrediction
> = core.serialization.object({
    metadata: core.serialization.lazyObject(async () => (await import("..")).TranscriptionMetadata).optional(),
    groupedPredictions: core.serialization.property(
        "grouped_predictions",
        core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).GroupedPredictionsNerPrediction)
        )
    ),
});

export declare namespace PredictionsOptionalTranscriptionMetadataNerPrediction {
    interface Raw {
        metadata?: serializers.TranscriptionMetadata.Raw | null;
        grouped_predictions: serializers.GroupedPredictionsNerPrediction.Raw[];
    }
}
