/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hume from "../../api";
import * as core from "../../core";

export const StateInProgress: core.serialization.ObjectSchema<serializers.StateInProgress.Raw, Hume.StateInProgress> =
    core.serialization.object({
        status: core.serialization.string().optional(),
    });

export declare namespace StateInProgress {
    interface Raw {
        status?: string | null;
    }
}
