/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Hume from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ReturnUserDefinedTool } from "../../../types/ReturnUserDefinedTool";
export declare const Response: core.serialization.Schema<
    serializers.empathicVoice.tools.updateToolDescription.Response.Raw,
    Hume.empathicVoice.ReturnUserDefinedTool | undefined
>;
export declare namespace Response {
    type Raw = ReturnUserDefinedTool.Raw | null | undefined;
}
