/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../../..";

/**
 * Response for the speech prosody emotion model.
 */
export interface StreamBurstProsody {
    predictions?: Hume.expressionMeasurement.StreamBurstProsodyPredictionsItem[];
}
