/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../../index.js";
import * as Hume from "../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../core/index.js";
import { SubscribeEvent } from "../../types/SubscribeEvent.js";

export const StreamSocketResponse: core.serialization.Schema<
    serializers.expressionMeasurement.stream.StreamSocketResponse.Raw,
    Hume.expressionMeasurement.stream.SubscribeEvent
> = core.serialization.undiscriminatedUnion([SubscribeEvent]);

export declare namespace StreamSocketResponse {
    export type Raw = SubscribeEvent.Raw;
}
