/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ValidationError } from "./ValidationError";
export const HttpValidationError = core.serialization.object({
    detail: core.serialization.list(ValidationError).optional(),
});
