/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { PostedContext } from "./PostedContext";
import { PostedUtterance } from "./PostedUtterance";
import { Format } from "./Format";
export declare const PostedTts: core.serialization.ObjectSchema<serializers.tts.PostedTts.Raw, Hume.tts.PostedTts>;
export declare namespace PostedTts {
    interface Raw {
        context?: PostedContext.Raw | null;
        utterances: PostedUtterance.Raw[];
        num_generations?: number | null;
        format?: Format.Raw | null;
        split_utterances?: boolean | null;
        strip_headers?: boolean | null;
        instant_mode?: boolean | null;
    }
}
