/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { PostedContextWithGenerationId } from "./PostedContextWithGenerationId";
import { PostedContextWithUtterances } from "./PostedContextWithUtterances";
export const PostedContext = core.serialization.undiscriminatedUnion([
    PostedContextWithGenerationId,
    PostedContextWithUtterances,
]);
