/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { ReturnGeneration } from "./ReturnGeneration";
export declare const ReturnTts: core.serialization.ObjectSchema<serializers.tts.ReturnTts.Raw, Hume.tts.ReturnTts>;
export declare namespace ReturnTts {
    interface Raw {
        request_id?: string | null;
        generations: ReturnGeneration.Raw[];
    }
}
