/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { ReturnVoice } from "./ReturnVoice";
export declare const ReturnPagedVoices: core.serialization.ObjectSchema<
    serializers.tts.ReturnPagedVoices.Raw,
    Hume.tts.ReturnPagedVoices
>;
export declare namespace ReturnPagedVoices {
    interface Raw {
        page_number?: number | null;
        page_size?: number | null;
        total_pages?: number | null;
        voices_page?: ReturnVoice.Raw[] | null;
    }
}
