/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
export declare const Snippet: core.serialization.ObjectSchema<serializers.tts.Snippet.Raw, Hume.tts.Snippet>;
export declare namespace Snippet {
    interface Raw {
        id: string;
        text: string;
        generation_id: string;
        utterance_index?: number | null;
        transcribed_text?: string | null;
        audio: string;
    }
}
