/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { AudioFormatType } from "./AudioFormatType";
import { Snippet } from "./Snippet";
export const SnippetAudioChunk = core.serialization.object({
    generationId: core.serialization.property("generation_id", core.serialization.string()),
    snippetId: core.serialization.property("snippet_id", core.serialization.string()),
    text: core.serialization.string(),
    transcribedText: core.serialization.property("transcribed_text", core.serialization.string().optional()),
    chunkIndex: core.serialization.property("chunk_index", core.serialization.number()),
    audio: core.serialization.string(),
    audioFormat: core.serialization.property("audio_format", AudioFormatType),
    isLastChunk: core.serialization.property("is_last_chunk", core.serialization.boolean()),
    utteranceIndex: core.serialization.property("utterance_index", core.serialization.number().optional()),
    snippet: Snippet,
});
