// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const PostedPromptName: core.serialization.Schema<
    serializers.empathicVoice.PostedPromptName.Raw,
    Hume.empathicVoice.PostedPromptName
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace PostedPromptName {
    export interface Raw {
        name: string;
    }
}
