/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../../../index';
import * as Hume from '../../../../../../api/index';
import * as core from '../../../../../../core';
import { ReturnUserDefinedTool } from '../../../types/ReturnUserDefinedTool';

export const Response: core.serialization.Schema<
  serializers.empathicVoice.tools.createToolVersion.Response.Raw,
  Hume.empathicVoice.ReturnUserDefinedTool | undefined
> = ReturnUserDefinedTool.optional();

export declare namespace Response {
  type Raw = ReturnUserDefinedTool.Raw | null | undefined;
}
