/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Hume from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { StreamModelPredictionsLanguagePredictionsItem } from "./StreamModelPredictionsLanguagePredictionsItem";
export declare const StreamModelPredictionsLanguage: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.stream.StreamModelPredictionsLanguage.Raw,
    Hume.expressionMeasurement.stream.StreamModelPredictionsLanguage
>;
export declare namespace StreamModelPredictionsLanguage {
    interface Raw {
        predictions?: StreamModelPredictionsLanguagePredictionsItem.Raw[] | null;
    }
}
