/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../../../../core";
import { StreamBoundingBox } from "../../../types/StreamBoundingBox";
import { EmotionEmbedding } from "../../../types/EmotionEmbedding";
export const StreamModelPredictionsFacePredictionsItem = core.serialization.object({
    frame: core.serialization.number().optional(),
    time: core.serialization.number().optional(),
    bbox: StreamBoundingBox.optional(),
    prob: core.serialization.number().optional(),
    faceId: core.serialization.property("face_id", core.serialization.string().optional()),
    emotions: EmotionEmbedding.optional(),
    facs: EmotionEmbedding.optional(),
    descriptions: EmotionEmbedding.optional(),
});
