/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Hume from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
export declare const StreamLanguage: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.stream.StreamLanguage.Raw,
    Hume.expressionMeasurement.stream.StreamLanguage
>;
export declare namespace StreamLanguage {
    interface Raw {
        sentiment?: Record<string, unknown> | null;
        toxicity?: Record<string, unknown> | null;
        granularity?: string | null;
    }
}
