/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";

export const WebsocketBurstFacemeshPredictionsItem: core.serialization.ObjectSchema<
    serializers.WebsocketBurstFacemeshPredictionsItem.Raw,
    Hume.WebsocketBurstFacemeshPredictionsItem
> = core.serialization.object({
    emotions: core.serialization.lazy(async () => (await import("../../..")).EmotionEmbedding).optional(),
});

export declare namespace WebsocketBurstFacemeshPredictionsItem {
    interface Raw {
        emotions?: serializers.EmotionEmbedding.Raw | null;
    }
}
