// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { StreamModelPredictionsProsodyPredictionsItem } from "./StreamModelPredictionsProsodyPredictionsItem.js";

export const StreamModelPredictionsProsody: core.serialization.ObjectSchema<
    serializers.expressionMeasurement.stream.StreamModelPredictionsProsody.Raw,
    Hume.expressionMeasurement.stream.StreamModelPredictionsProsody
> = core.serialization.object({
    predictions: core.serialization.list(StreamModelPredictionsProsodyPredictionsItem).optional(),
});

export declare namespace StreamModelPredictionsProsody {
    export interface Raw {
        predictions?: StreamModelPredictionsProsodyPredictionsItem.Raw[] | null;
    }
}
