// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AssistantInput: core.serialization.ObjectSchema<
    serializers.empathicVoice.AssistantInput.Raw,
    Hume.empathicVoice.AssistantInput
> = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    text: core.serialization.string(),
    type: core.serialization.stringLiteral("assistant_input"),
});

export declare namespace AssistantInput {
    export interface Raw {
        custom_session_id?: string | null;
        text: string;
        type: "assistant_input";
    }
}
