/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const BuiltinToolType: core.serialization.Schema<
    serializers.empathicVoice.BuiltinToolType.Raw,
    Hume.empathicVoice.BuiltinToolType
> = core.serialization.enum_(["web_search", "hang_up"]);

export declare namespace BuiltinToolType {
    type Raw = "web_search" | "hang_up";
}
