// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ConnectSessionSettingsAudio: core.serialization.ObjectSchema<
    serializers.empathicVoice.ConnectSessionSettingsAudio.Raw,
    Hume.empathicVoice.ConnectSessionSettingsAudio
> = core.serialization.object({
    channels: core.serialization.number().optional(),
    encoding: core.serialization.string().optional(),
    sampleRate: core.serialization.property("sample_rate", core.serialization.number().optional()),
});

export declare namespace ConnectSessionSettingsAudio {
    export interface Raw {
        channels?: number | null;
        encoding?: string | null;
        sample_rate?: number | null;
    }
}
