/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ContextType } from "./ContextType.js";

export const Context: core.serialization.ObjectSchema<
    serializers.empathicVoice.Context.Raw,
    Hume.empathicVoice.Context
> = core.serialization.object({
    text: core.serialization.string(),
    type: ContextType.optional(),
});

export declare namespace Context {
    export interface Raw {
        text: string;
        type?: ContextType.Raw | null;
    }
}
