// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const InterruptionSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.InterruptionSpec.Raw,
    Hume.empathicVoice.InterruptionSpec
> = core.serialization.object({
    minInterruptionMs: core.serialization.property("min_interruption_ms", core.serialization.number().optional()),
});

export declare namespace InterruptionSpec {
    export interface Raw {
        min_interruption_ms?: number | null;
    }
}
