/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { SupportedLanguageModelEndpoint } from "./SupportedLanguageModelEndpoint";

export const LanguageModelEndpointResponse: core.serialization.ObjectSchema<
    serializers.empathicVoice.LanguageModelEndpointResponse.Raw,
    Hume.empathicVoice.LanguageModelEndpointResponse
> = core.serialization.object({
    languageModels: core.serialization.property(
        "language_models",
        core.serialization.list(SupportedLanguageModelEndpoint)
    ),
});

export declare namespace LanguageModelEndpointResponse {
    interface Raw {
        language_models: SupportedLanguageModelEndpoint.Raw[];
    }
}
