/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const PostedLanguageModelModelProvider: core.serialization.Schema<
    serializers.empathicVoice.PostedLanguageModelModelProvider.Raw,
    Hume.empathicVoice.PostedLanguageModelModelProvider
> = core.serialization.enum_(["OPEN_AI", "CUSTOM_LANGUAGE_MODEL", "ANTHROPIC", "FIREWORKS", "GROQ", "GOOGLE"]);

export declare namespace PostedLanguageModelModelProvider {
    export type Raw = "OPEN_AI" | "CUSTOM_LANGUAGE_MODEL" | "ANTHROPIC" | "FIREWORKS" | "GROQ" | "GOOGLE";
}
