// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { PostedTimeoutSpecsInactivity } from "./PostedTimeoutSpecsInactivity.js";
import { PostedTimeoutSpecsMaxDuration } from "./PostedTimeoutSpecsMaxDuration.js";

export const PostedTimeoutSpecs: core.serialization.ObjectSchema<
    serializers.empathicVoice.PostedTimeoutSpecs.Raw,
    Hume.empathicVoice.PostedTimeoutSpecs
> = core.serialization.object({
    inactivity: PostedTimeoutSpecsInactivity.optional(),
    maxDuration: core.serialization.property("max_duration", PostedTimeoutSpecsMaxDuration.optional()),
});

export declare namespace PostedTimeoutSpecs {
    export interface Raw {
        inactivity?: PostedTimeoutSpecsInactivity.Raw | null;
        max_duration?: PostedTimeoutSpecsMaxDuration.Raw | null;
    }
}
