/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { VoiceRef } from "./VoiceRef";
import { ReturnCustomVoice } from "./ReturnCustomVoice";

export const PostedVoice: core.serialization.Schema<
    serializers.empathicVoice.PostedVoice.Raw,
    Hume.empathicVoice.PostedVoice
> = core.serialization.undiscriminatedUnion([VoiceRef, ReturnCustomVoice]);

export declare namespace PostedVoice {
    export type Raw = VoiceRef.Raw | ReturnCustomVoice.Raw;
}
