/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const PostedCustomVoiceBaseVoice: core.serialization.Schema<
    serializers.empathicVoice.PostedCustomVoiceBaseVoice.Raw,
    Hume.empathicVoice.PostedCustomVoiceBaseVoice
> = core.serialization.enum_(["ITO", "KORA", "DACHER", "AURA", "FINN", "WHIMSY", "STELLA", "SUNNY"]);

export declare namespace PostedCustomVoiceBaseVoice {
    export type Raw = "ITO" | "KORA" | "DACHER" | "AURA" | "FINN" | "WHIMSY" | "STELLA" | "SUNNY";
}
