// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const PostedEventMessageSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.PostedEventMessageSpec.Raw,
    Hume.empathicVoice.PostedEventMessageSpec
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    text: core.serialization.string().optionalNullable(),
});

export declare namespace PostedEventMessageSpec {
    export interface Raw {
        enabled: boolean;
        text?: (string | null | undefined) | null;
    }
}
