// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const PostedTimeoutSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.PostedTimeoutSpec.Raw,
    Hume.empathicVoice.PostedTimeoutSpec
> = core.serialization.object({
    durationSecs: core.serialization.property("duration_secs", core.serialization.number().optionalNullable()),
    enabled: core.serialization.boolean(),
});

export declare namespace PostedTimeoutSpec {
    export interface Raw {
        duration_secs?: (number | null | undefined) | null;
        enabled: boolean;
    }
}
