/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const PostedNudgeSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.PostedNudgeSpec.Raw,
    Hume.empathicVoice.PostedNudgeSpec
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
    intervalSecs: core.serialization.property("interval_secs", core.serialization.number().optional()),
});

export declare namespace PostedNudgeSpec {
    export interface Raw {
        enabled?: boolean | null;
        interval_secs?: number | null;
    }
}
