// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ResumeAssistantMessageType: core.serialization.Schema<
    serializers.empathicVoice.ResumeAssistantMessageType.Raw,
    Hume.empathicVoice.ResumeAssistantMessageType
> = core.serialization.enum_(["resume_assistant_message"]);

export declare namespace ResumeAssistantMessageType {
    export type Raw = "resume_assistant_message";
}
