/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnTimeoutSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnTimeoutSpec.Raw,
    Hume.empathicVoice.ReturnTimeoutSpec
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    durationSecs: core.serialization.property("duration_secs", core.serialization.number().optional()),
});

export declare namespace ReturnTimeoutSpec {
    interface Raw {
        enabled: boolean;
        duration_secs?: number | null;
    }
}
