/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ReturnWebhookEventType: core.serialization.Schema<
    serializers.empathicVoice.ReturnWebhookEventType.Raw,
    Hume.empathicVoice.ReturnWebhookEventType
> = core.serialization.enum_(["chat_started", "chat_ended"]);

export declare namespace ReturnWebhookEventType {
    export type Raw = "chat_started" | "chat_ended";
}
