/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnChatStatus: core.serialization.Schema<
    serializers.empathicVoice.ReturnChatStatus.Raw,
    Hume.empathicVoice.ReturnChatStatus
> = core.serialization.enum_([
    "ACTIVE",
    "USER_ENDED",
    "USER_TIMEOUT",
    "MAX_DURATION_TIMEOUT",
    "INACTIVITY_TIMEOUT",
    "ERROR",
]);

export declare namespace ReturnChatStatus {
    export type Raw =
        | "ACTIVE"
        | "USER_ENDED"
        | "USER_TIMEOUT"
        | "MAX_DURATION_TIMEOUT"
        | "INACTIVITY_TIMEOUT"
        | "ERROR";
}
