/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnChatAudioReconstructionStatus: core.serialization.Schema<
    serializers.empathicVoice.ReturnChatAudioReconstructionStatus.Raw,
    Hume.empathicVoice.ReturnChatAudioReconstructionStatus
> = core.serialization.enum_(["QUEUED", "IN_PROGRESS", "COMPLETE", "ERROR", "CANCELLED"]);

export declare namespace ReturnChatAudioReconstructionStatus {
    export type Raw = "QUEUED" | "IN_PROGRESS" | "COMPLETE" | "ERROR" | "CANCELLED";
}
