/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnVoiceEvi2: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnVoiceEvi2.Raw,
    Hume.empathicVoice.ReturnVoiceEvi2
> = core.serialization.object({
    id: core.serialization.string(),
    version: core.serialization.number(),
    name: core.serialization.string(),
    createdOn: core.serialization.property("created_on", core.serialization.number()),
    modifiedOn: core.serialization.property("modified_on", core.serialization.number()),
    baseVoice: core.serialization.property("base_voice", core.serialization.string()),
    speechRateMultiplier: core.serialization.property("speech_rate_multiplier", core.serialization.number().optional()),
    parameterModel: core.serialization.property("parameter_model", core.serialization.string()),
    parameters: core.serialization.record(core.serialization.string(), core.serialization.number()),
});

export declare namespace ReturnVoiceEvi2 {
    export interface Raw {
        id: string;
        version: number;
        name: string;
        created_on: number;
        modified_on: number;
        base_voice: string;
        speech_rate_multiplier?: number | null;
        parameter_model: string;
        parameters: Record<string, number>;
    }
}
