/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { ReturnVoiceOctavePublicProvider } from "./ReturnVoiceOctavePublicProvider";

export const ReturnVoiceOctavePublic: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnVoiceOctavePublic.Raw,
    Hume.empathicVoice.ReturnVoiceOctavePublic
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    provider: ReturnVoiceOctavePublicProvider.optional(),
});

export declare namespace ReturnVoiceOctavePublic {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        provider?: ReturnVoiceOctavePublicProvider.Raw | null;
    }
}
