// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ReturnTimeoutSpec: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnTimeoutSpec.Raw,
    Hume.empathicVoice.ReturnTimeoutSpec
> = core.serialization.object({
    durationSecs: core.serialization.property("duration_secs", core.serialization.number().optional()),
    enabled: core.serialization.boolean(),
});

export declare namespace ReturnTimeoutSpec {
    export interface Raw {
        duration_secs?: number | null;
        enabled: boolean;
    }
}
