/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnPrivacySettings: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnPrivacySettings.Raw,
    Hume.empathicVoice.ReturnPrivacySettings
> = core.serialization.object({
    id: core.serialization.string().optional(),
    doNotRetainData: core.serialization.property("do_not_retain_data", core.serialization.boolean().optional()),
    doNotUseForTraining: core.serialization.property(
        "do_not_use_for_training",
        core.serialization.boolean().optional()
    ),
});

export declare namespace ReturnPrivacySettings {
    interface Raw {
        id?: string | null;
        do_not_retain_data?: boolean | null;
        do_not_use_for_training?: boolean | null;
    }
}
