/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ReturnConfigSpec } from "./ReturnConfigSpec.js";

export const ReturnChatGroup: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnChatGroup.Raw,
    Hume.empathicVoice.ReturnChatGroup
> = core.serialization.object({
    id: core.serialization.string(),
    firstStartTimestamp: core.serialization.property("first_start_timestamp", core.serialization.number()),
    mostRecentStartTimestamp: core.serialization.property("most_recent_start_timestamp", core.serialization.number()),
    mostRecentChatId: core.serialization.property("most_recent_chat_id", core.serialization.string().optional()),
    mostRecentConfig: core.serialization.property("most_recent_config", ReturnConfigSpec.optional()),
    numChats: core.serialization.property("num_chats", core.serialization.number()),
    active: core.serialization.boolean().optional(),
});

export declare namespace ReturnChatGroup {
    export interface Raw {
        id: string;
        first_start_timestamp: number;
        most_recent_start_timestamp: number;
        most_recent_chat_id?: string | null;
        most_recent_config?: ReturnConfigSpec.Raw | null;
        num_chats: number;
        active?: boolean | null;
    }
}
