/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { ReturnUserDefinedTool } from "./ReturnUserDefinedTool";

export const ReturnPagedUserDefinedTools: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnPagedUserDefinedTools.Raw,
    Hume.empathicVoice.ReturnPagedUserDefinedTools
> = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
    toolsPage: core.serialization.property("tools_page", core.serialization.list(ReturnUserDefinedTool.optional())),
});

export declare namespace ReturnPagedUserDefinedTools {
    interface Raw {
        page_number: number;
        page_size: number;
        total_pages: number;
        tools_page: (ReturnUserDefinedTool.Raw | null | undefined)[];
    }
}
