/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";

export const ReturnActiveChatCountPerTag: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnActiveChatCountPerTag.Raw,
    Hume.empathicVoice.ReturnActiveChatCountPerTag
> = core.serialization.object({
    tag: core.serialization.string(),
    totalTagActiveChats: core.serialization.property("total_tag_active_chats", core.serialization.number()),
});

export declare namespace ReturnActiveChatCountPerTag {
    interface Raw {
        tag: string;
        total_tag_active_chats: number;
    }
}
