// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ReturnChatGroup } from "./ReturnChatGroup.js";
import { ReturnPagedChatGroupsPaginationDirection } from "./ReturnPagedChatGroupsPaginationDirection.js";

export const ReturnPagedChatGroups: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnPagedChatGroups.Raw,
    Hume.empathicVoice.ReturnPagedChatGroups
> = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
    paginationDirection: core.serialization.property("pagination_direction", ReturnPagedChatGroupsPaginationDirection),
    chatGroupsPage: core.serialization.property("chat_groups_page", core.serialization.list(ReturnChatGroup)),
});

export declare namespace ReturnPagedChatGroups {
    export interface Raw {
        page_number: number;
        page_size: number;
        total_pages: number;
        pagination_direction: ReturnPagedChatGroupsPaginationDirection.Raw;
        chat_groups_page: ReturnChatGroup.Raw[];
    }
}
