/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";
import { ReturnChat } from "./ReturnChat";

export const ReturnPagedChats: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnPagedChats.Raw,
    Hume.empathicVoice.ReturnPagedChats
> = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number().optional()),
    pageSize: core.serialization.property("page_size", core.serialization.number().optional()),
    chatsPage: core.serialization.property("chats_page", core.serialization.list(ReturnChat).optional()),
});

export declare namespace ReturnPagedChats {
    interface Raw {
        page_number?: number | null;
        page_size?: number | null;
        chats_page?: ReturnChat.Raw[] | null;
    }
}
