// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ReturnTimeoutSpec } from "./ReturnTimeoutSpec.js";

export const ReturnConfigTimeouts: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnConfigTimeouts.Raw,
    Hume.empathicVoice.ReturnConfigTimeouts
> = core.serialization.object({
    inactivity: ReturnTimeoutSpec,
    maxDuration: core.serialization.property("max_duration", ReturnTimeoutSpec),
});

export declare namespace ReturnConfigTimeouts {
    export interface Raw {
        inactivity: ReturnTimeoutSpec.Raw;
        max_duration: ReturnTimeoutSpec.Raw;
    }
}
