// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ReturnUserDefinedTool } from "./ReturnUserDefinedTool.js";

export const ReturnPagedUserDefinedTools: core.serialization.ObjectSchema<
    serializers.empathicVoice.ReturnPagedUserDefinedTools.Raw,
    Hume.empathicVoice.ReturnPagedUserDefinedTools
> = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    toolsPage: core.serialization.property("tools_page", core.serialization.list(ReturnUserDefinedTool.nullable())),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});

export declare namespace ReturnPagedUserDefinedTools {
    export interface Raw {
        page_number: number;
        page_size: number;
        tools_page: (ReturnUserDefinedTool.Raw | null | undefined)[];
        total_pages: number;
    }
}
