/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../index';
import * as Hume from '../../../../api/index';
import * as core from '../../../../core';

export const TextInput: core.serialization.ObjectSchema<
  serializers.empathicVoice.TextInput.Raw,
  Hume.empathicVoice.TextInput
> = core.serialization.object({
  type: core.serialization.stringLiteral('text_input').optional(),
});

export declare namespace TextInput {
  interface Raw {
    type?: 'text_input' | null;
  }
}
