// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ToolResponseMessageType } from "./ToolResponseMessageType.js";
import { ToolType } from "./ToolType.js";

export const ToolResponseMessage: core.serialization.ObjectSchema<
    serializers.empathicVoice.ToolResponseMessage.Raw,
    Hume.empathicVoice.ToolResponseMessage
> = core.serialization.object({
    content: core.serialization.string(),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optionalNullable()),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    toolName: core.serialization.property("tool_name", core.serialization.string().optionalNullable()),
    toolType: core.serialization.property("tool_type", ToolType.optionalNullable()),
    type: ToolResponseMessageType,
});

export declare namespace ToolResponseMessage {
    export interface Raw {
        content: string;
        custom_session_id?: (string | null | undefined) | null;
        tool_call_id: string;
        tool_name?: (string | null | undefined) | null;
        tool_type?: (ToolType.Raw | null | undefined) | null;
        type: ToolResponseMessageType.Raw;
    }
}
