// This file was auto-generated by Fern from our API Definition.

import type * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ToolCallMessageType: core.serialization.Schema<
    serializers.empathicVoice.ToolCallMessageType.Raw,
    Hume.empathicVoice.ToolCallMessageType
> = core.serialization.enum_(["tool_call"]);

export declare namespace ToolCallMessageType {
    export type Raw = "tool_call";
}
