/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Hume from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ToolType } from "./ToolType.js";

export const Tool: core.serialization.ObjectSchema<serializers.empathicVoice.Tool.Raw, Hume.empathicVoice.Tool> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
        name: core.serialization.string(),
        parameters: core.serialization.string(),
        type: ToolType,
    });

export declare namespace Tool {
    export interface Raw {
        description?: string | null;
        fallback_content?: string | null;
        name: string;
        parameters: string;
        type: ToolType.Raw;
    }
}
