/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hume from "../../../../api";
import * as core from "../../../../core";

export const UserInterruption: core.serialization.ObjectSchema<
    serializers.empathicVoice.UserInterruption.Raw,
    Hume.empathicVoice.UserInterruption
> = core.serialization.object({
    time: core.serialization.number(),
    type: core.serialization.stringLiteral("user_interruption"),
});

export declare namespace UserInterruption {
    interface Raw {
        time: number;
        type: "user_interruption";
    }
}
