/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../index';
import * as Hume from '../../../../api/index';
import * as core from '../../../../core';
import { ChatMessage } from './ChatMessage';
import { Inference } from './Inference';
import { MillisecondInterval } from './MillisecondInterval';

export const UserMessage: core.serialization.ObjectSchema<
  serializers.empathicVoice.UserMessage.Raw,
  Hume.empathicVoice.UserMessage
> = core.serialization.object({
  type: core.serialization.stringLiteral('user_message'),
  customSessionId: core.serialization.property(
    'custom_session_id',
    core.serialization.string().optional(),
  ),
  message: ChatMessage,
  models: Inference,
  time: MillisecondInterval,
  fromText: core.serialization.property(
    'from_text',
    core.serialization.boolean(),
  ),
});

export declare namespace UserMessage {
  interface Raw {
    type: 'user_message';
    custom_session_id?: string | null;
    message: ChatMessage.Raw;
    models: Inference.Raw;
    time: MillisecondInterval.Raw;
    from_text: boolean;
  }
}
