/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hume from "../../../../api/index";
import * as core from "../../../../core";
import { PostedCustomVoice } from "./PostedCustomVoice";

export const VoiceEvi2: core.serialization.ObjectSchema<
    serializers.empathicVoice.VoiceEvi2.Raw,
    Hume.empathicVoice.VoiceEvi2
> = core.serialization.object({
    provider: core.serialization.string(),
    customVoice: core.serialization.property("custom_voice", PostedCustomVoice.optional()),
});

export declare namespace VoiceEvi2 {
    export interface Raw {
        provider: string;
        custom_voice?: PostedCustomVoice.Raw | null;
    }
}
