/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hume from "../../../../../..";

/**
 * @example
 *     {}
 */
export interface PostedConfigVersion {
    /** Description that is appended to a specific version of a Config. */
    versionDescription?: string;
    prompt?: Hume.empathicVoice.PostedPromptSpec;
    languageModel?: Hume.empathicVoice.PostedLanguageModel;
}
