/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PostedConfigVersionDescription {
  /** An optional description of the Config version. */
  versionDescription?: string;
}
