// This file was auto-generated by Fern from our API Definition.

export interface HumeEnvironmentUrls {
    base: string;
    evi: string;
    tts: string;
    stream: string;
}

export const HumeEnvironment = {
    Prod: {
        base: "https://api.hume.ai",
        evi: "wss://api.hume.ai/v0/evi",
        tts: "wss://api.hume.ai/v0/tts",
        stream: "wss://api.hume.ai/v0/stream",
    },
} as const;

export type HumeEnvironment = typeof HumeEnvironment.Prod;
