/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool.js";
import { HumeClient } from "../../../src/Client";

describe("Configs", () => {
    test("create-config", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Weather Assistant Config",
            prompt: { id: "af699d45-2985-42cc-91b9-af9e5da3bac5", version: 0 },
            evi_version: "2",
            voice: { provider: "HUME_AI", name: "SAMPLE VOICE" },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
        };
        const rawResponseBody = {
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 0,
            version_description: "",
            name: "Weather Assistant Config",
            created_on: 1715275452390,
            modified_on: 1715275452390,
            evi_version: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                version_type: "FIXED",
                version_description: "",
                name: "Weather Assistant Prompt",
                created_on: 1715267200693,
                modified_on: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                custom_voice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    created_on: 1724704587367,
                    modified_on: 1725489961583,
                    base_voice: "KORA",
                    parameter_model: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            ellm_model: { allow_short_responses: false },
            tools: [],
            builtin_tools: [],
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
            timeouts: {
                inactivity: { enabled: true, duration_secs: 600 },
                max_duration: { enabled: true, duration_secs: 1800 },
            },
        };
        server
            .mockEndpoint()
            .post("/v0/evi/configs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.empathicVoice.configs.createConfig({
            name: "Weather Assistant Config",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
            },
            eviVersion: "2",
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
            },
            languageModel: {
                modelProvider: "ANTHROPIC",
                modelResource: "claude-3-7-sonnet-latest",
                temperature: 1,
            },
            eventMessages: {
                onNewChat: {
                    enabled: false,
                    text: "",
                },
                onInactivityTimeout: {
                    enabled: false,
                    text: "",
                },
                onMaxDurationTimeout: {
                    enabled: false,
                    text: "",
                },
            },
        });
        expect(response).toEqual({
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 0,
            versionDescription: "",
            name: "Weather Assistant Config",
            createdOn: 1715275452390,
            modifiedOn: 1715275452390,
            eviVersion: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                versionType: "FIXED",
                versionDescription: "",
                name: "Weather Assistant Prompt",
                createdOn: 1715267200693,
                modifiedOn: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                customVoice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    createdOn: 1724704587367,
                    modifiedOn: 1725489961583,
                    baseVoice: "KORA",
                    parameterModel: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            languageModel: {
                modelProvider: "ANTHROPIC",
                modelResource: "claude-3-7-sonnet-latest",
                temperature: 1,
            },
            ellmModel: {
                allowShortResponses: false,
            },
            tools: [],
            builtinTools: [],
            eventMessages: {
                onNewChat: {
                    enabled: false,
                    text: "",
                },
                onInactivityTimeout: {
                    enabled: false,
                    text: "",
                },
                onMaxDurationTimeout: {
                    enabled: false,
                    text: "",
                },
            },
            timeouts: {
                inactivity: {
                    enabled: true,
                    durationSecs: 600,
                },
                maxDuration: {
                    enabled: true,
                    durationSecs: 1800,
                },
            },
        });
    });

    test("create-config-version", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            version_description: "This is an updated version of the Weather Assistant Config.",
            evi_version: "2",
            prompt: { id: "af699d45-2985-42cc-91b9-af9e5da3bac5", version: 0 },
            voice: { provider: "HUME_AI", name: "ITO" },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            ellm_model: { allow_short_responses: true },
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
        };
        const rawResponseBody = {
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            version_description: "This is an updated version of the Weather Assistant Config.",
            name: "Weather Assistant Config",
            created_on: 1715275452390,
            modified_on: 1722642242998,
            evi_version: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                version_type: "FIXED",
                version_description: "",
                name: "Weather Assistant Prompt",
                created_on: 1715267200693,
                modified_on: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "ITO",
                custom_voice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    created_on: 1724704587367,
                    modified_on: 1725489961583,
                    base_voice: "KORA",
                    parameter_model: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            ellm_model: { allow_short_responses: true },
            tools: [],
            builtin_tools: [],
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
            timeouts: {
                inactivity: { enabled: true, duration_secs: 600 },
                max_duration: { enabled: true, duration_secs: 1800 },
            },
        };
        server
            .mockEndpoint()
            .post("/v0/evi/configs/1b60e1a0-cc59-424a-8d2c-189d354db3f3")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.empathicVoice.configs.createConfigVersion(
            "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            {
                versionDescription: "This is an updated version of the Weather Assistant Config.",
                eviVersion: "2",
                prompt: {
                    id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                    version: 0,
                },
                voice: {
                    provider: "HUME_AI",
                    name: "ITO",
                },
                languageModel: {
                    modelProvider: "ANTHROPIC",
                    modelResource: "claude-3-7-sonnet-latest",
                    temperature: 1,
                },
                ellmModel: {
                    allowShortResponses: true,
                },
                eventMessages: {
                    onNewChat: {
                        enabled: false,
                        text: "",
                    },
                    onInactivityTimeout: {
                        enabled: false,
                        text: "",
                    },
                    onMaxDurationTimeout: {
                        enabled: false,
                        text: "",
                    },
                },
            },
        );
        expect(response).toEqual({
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            versionDescription: "This is an updated version of the Weather Assistant Config.",
            name: "Weather Assistant Config",
            createdOn: 1715275452390,
            modifiedOn: 1722642242998,
            eviVersion: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                versionType: "FIXED",
                versionDescription: "",
                name: "Weather Assistant Prompt",
                createdOn: 1715267200693,
                modifiedOn: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "ITO",
                customVoice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    createdOn: 1724704587367,
                    modifiedOn: 1725489961583,
                    baseVoice: "KORA",
                    parameterModel: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            languageModel: {
                modelProvider: "ANTHROPIC",
                modelResource: "claude-3-7-sonnet-latest",
                temperature: 1,
            },
            ellmModel: {
                allowShortResponses: true,
            },
            tools: [],
            builtinTools: [],
            eventMessages: {
                onNewChat: {
                    enabled: false,
                    text: "",
                },
                onInactivityTimeout: {
                    enabled: false,
                    text: "",
                },
                onMaxDurationTimeout: {
                    enabled: false,
                    text: "",
                },
            },
            timeouts: {
                inactivity: {
                    enabled: true,
                    durationSecs: 600,
                },
                maxDuration: {
                    enabled: true,
                    durationSecs: 1800,
                },
            },
        });
    });

    test("delete-config", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/v0/evi/configs/1b60e1a0-cc59-424a-8d2c-189d354db3f3")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.empathicVoice.configs.deleteConfig("1b60e1a0-cc59-424a-8d2c-189d354db3f3");
        expect(response).toEqual(undefined);
    });

    test("get-config-version", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            version_description: "",
            name: "Weather Assistant Config",
            created_on: 1715275452390,
            modified_on: 1715275452390,
            evi_version: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                version_type: "FIXED",
                version_description: "",
                name: "Weather Assistant Prompt",
                created_on: 1715267200693,
                modified_on: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                custom_voice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    created_on: 1724704587367,
                    modified_on: 1725489961583,
                    base_voice: "KORA",
                    parameter_model: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            ellm_model: { allow_short_responses: false },
            tools: [],
            builtin_tools: [],
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
            timeouts: {
                inactivity: { enabled: true, duration_secs: 600 },
                max_duration: { enabled: true, duration_secs: 1800 },
            },
        };
        server
            .mockEndpoint()
            .get("/v0/evi/configs/1b60e1a0-cc59-424a-8d2c-189d354db3f3/version/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.empathicVoice.configs.getConfigVersion("1b60e1a0-cc59-424a-8d2c-189d354db3f3", 1);
        expect(response).toEqual({
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            versionDescription: "",
            name: "Weather Assistant Config",
            createdOn: 1715275452390,
            modifiedOn: 1715275452390,
            eviVersion: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                versionType: "FIXED",
                versionDescription: "",
                name: "Weather Assistant Prompt",
                createdOn: 1715267200693,
                modifiedOn: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                customVoice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    createdOn: 1724704587367,
                    modifiedOn: 1725489961583,
                    baseVoice: "KORA",
                    parameterModel: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            languageModel: {
                modelProvider: "ANTHROPIC",
                modelResource: "claude-3-7-sonnet-latest",
                temperature: 1,
            },
            ellmModel: {
                allowShortResponses: false,
            },
            tools: [],
            builtinTools: [],
            eventMessages: {
                onNewChat: {
                    enabled: false,
                    text: "",
                },
                onInactivityTimeout: {
                    enabled: false,
                    text: "",
                },
                onMaxDurationTimeout: {
                    enabled: false,
                    text: "",
                },
            },
            timeouts: {
                inactivity: {
                    enabled: true,
                    durationSecs: 600,
                },
                maxDuration: {
                    enabled: true,
                    durationSecs: 1800,
                },
            },
        });
    });

    test("delete-config-version", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/v0/evi/configs/1b60e1a0-cc59-424a-8d2c-189d354db3f3/version/1")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.empathicVoice.configs.deleteConfigVersion(
            "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            1,
        );
        expect(response).toEqual(undefined);
    });

    test("update-config-description", async () => {
        const server = mockServerPool.createServer();
        const client = new HumeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { version_description: "This is an updated version_description." };
        const rawResponseBody = {
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            version_description: "This is an updated version_description.",
            name: "Weather Assistant Config",
            created_on: 1715275452390,
            modified_on: 1715275452390,
            evi_version: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                version_type: "FIXED",
                version_description: "",
                name: "Weather Assistant Prompt",
                created_on: 1715267200693,
                modified_on: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                custom_voice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    created_on: 1724704587367,
                    modified_on: 1725489961583,
                    base_voice: "KORA",
                    parameter_model: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            language_model: { model_provider: "ANTHROPIC", model_resource: "claude-3-7-sonnet-latest", temperature: 1 },
            ellm_model: { allow_short_responses: false },
            tools: [],
            builtin_tools: [],
            event_messages: {
                on_new_chat: { enabled: false, text: "" },
                on_inactivity_timeout: { enabled: false, text: "" },
                on_max_duration_timeout: { enabled: false, text: "" },
            },
            timeouts: {
                inactivity: { enabled: true, duration_secs: 600 },
                max_duration: { enabled: true, duration_secs: 1800 },
            },
        };
        server
            .mockEndpoint()
            .patch("/v0/evi/configs/1b60e1a0-cc59-424a-8d2c-189d354db3f3/version/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.empathicVoice.configs.updateConfigDescription(
            "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            1,
            {
                versionDescription: "This is an updated version_description.",
            },
        );
        expect(response).toEqual({
            id: "1b60e1a0-cc59-424a-8d2c-189d354db3f3",
            version: 1,
            versionDescription: "This is an updated version_description.",
            name: "Weather Assistant Config",
            createdOn: 1715275452390,
            modifiedOn: 1715275452390,
            eviVersion: "2",
            prompt: {
                id: "af699d45-2985-42cc-91b9-af9e5da3bac5",
                version: 0,
                versionType: "FIXED",
                versionDescription: "",
                name: "Weather Assistant Prompt",
                createdOn: 1715267200693,
                modifiedOn: 1715267200693,
                text: "<role>You are an AI weather assistant providing users with accurate and up-to-date weather information. Respond to user queries concisely and clearly. Use simple language and avoid technical jargon. Provide temperature, precipitation, wind conditions, and any weather alerts. Include helpful tips if severe weather is expected.</role>",
            },
            voice: {
                provider: "HUME_AI",
                name: "SAMPLE VOICE",
                customVoice: {
                    id: "00aa8ee9-c50e-4ea1-9af0-7b08ad451704",
                    version: 1,
                    name: "SAMPLE VOICE",
                    createdOn: 1724704587367,
                    modifiedOn: 1725489961583,
                    baseVoice: "KORA",
                    parameterModel: "20241004-11parameter",
                    parameters: {
                        gender: 0,
                        assertiveness: 20,
                        buoyancy: -30,
                        confidence: -40,
                        enthusiasm: 50,
                        nasality: 45,
                        relaxedness: -35,
                        smoothness: 25,
                        tepidity: 15,
                        tightness: 5,
                    },
                },
            },
            languageModel: {
                modelProvider: "ANTHROPIC",
                modelResource: "claude-3-7-sonnet-latest",
                temperature: 1,
            },
            ellmModel: {
                allowShortResponses: false,
            },
            tools: [],
            builtinTools: [],
            eventMessages: {
                onNewChat: {
                    enabled: false,
                    text: "",
                },
                onInactivityTimeout: {
                    enabled: false,
                    text: "",
                },
                onMaxDurationTimeout: {
                    enabled: false,
                    text: "",
                },
            },
            timeouts: {
                inactivity: {
                    enabled: true,
                    durationSecs: 600,
                },
                maxDuration: {
                    enabled: true,
                    durationSecs: 1800,
                },
            },
        });
    });
});
